# Generated by Django 5.0.3 on 2024-09-06 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('dob', models.DateField(verbose_name='Date of Birth')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('department', models.CharField(max_length=50)),
                ('position', models.CharField(max_length=50)),
                ('date_of_hire', models.DateField()),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('contact_info', models.CharField(max_length=255)),
            ],
        ),
    ]
