# Generated by Django 5.0.3 on 2024-09-10 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_remove_employee_id_alter_employee_employee_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='contact_info',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='date_of_hire',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='salary',
        ),
    ]
